title:  Gabrielle Monkam
logo: "/images/Avatar Image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Analyst based in Virginia.
  <br><br>
  Experienced in collecting data, gathering requirements, preparing analysis and buiding efficient methodologies and process. 
  <br><br>
  <a href="https://www.https://www.linkedin.com/in/larissa-monkam-21516120b/">View My Linkedin Profile</a>
  <br><br>
  <a href="https://https://public.tableau.com/app/profile/gabrielle3296">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/gabriellemonkam/About-Me-Gabrielle-Monkam-99b8fb10714748ecb5cce9a72d4c5dce">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
